name: lapiscalc
description: "A simple calculator and unit converter app with Material Design 3."

publish_to: 'none'

version: 1.1.9

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  device_info_plus: ^11.5.0
  package_info_plus: ^8.0.0
  flutter_localizations:
    sdk: flutter
  animations: ^2.0.7
  cupertino_icons: ^1.0.2
  duration: ^4.0.3
  dynamic_color: ^1.8.1
  intl: any
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.12
  math_expressions: ^3.1.0
  provider: ^6.0.5
  responsive_builder: ^0.7.0
  shared_preferences: ^2.2.0
  units_converter: ^3.0.0
  url_launcher: ^6.1.11
  in_app_review: ^2.0.11



dev_dependencies:
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.5
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:

  generate: true
  uses-material-design: true
  assets:
    - assets/github-mark-white.svg
    - assets/github-mark.svg
    - assets/background_icon.png
  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope/Manrope-Regular.ttf


flutter_launcher_icons:
  android: true
  image_path: "launcher_icon_fg.png"
  min_sdk_android: 21
  web:
  generate: true
  background_color: "#002fc3"
  theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"